.PHONY: run-sfu run-signaling build-sfu build-signaling

run-sfu:
	go run ./cmd/sfu

run-signaling:
	go run ./cmd/signaling

build-sfu:
	go build -o bin/sfu ./cmd/sfu

build-signaling:
	go build -o bin/signaling ./cmd/signaling