apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  ingress.yaml: |
    log_level: info
    ws_url: ws://livekit.directlink-dev.svc.cluster.local:7880
    redis:
      address: redis.directlink-dev.svc.cluster.local:6379
    whip_port: 8080
    rtmp_port: 1935
    health_port: 8090
    prometheus_port: 9092