apiVersion: v1
kind: Service
metadata:
  name: livekit
  annotations:
    networking.gke.io/load-balancer-ip-addresses: directlink-dev-livekit
spec:
  type: LoadBalancer
  loadBalancerIP: 34.174.171.158