log_level: debug

# Blank strings will be overridden by env vars
api_key: ""
api_secret: ""
ws_url: ""

redis:
  address: localhost:6379

whip_port: 8080
rtmp_port: 1935

health_port: 8090
http_relay_port: 17932 # defaults to 9090 which conflicts with prometheus due to ingress requiring `network_mode: host` in docker. So set to obscure port to avoid conflicts.
prometheus_port: 9092