port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50200
  port_range_end: 50300
  use_ice_lite: true
prometheus_port: 9091
redis:
  address: redis:6379
keys:
  devkey: secret
webhook:
  api_key: devkey
  urls:
    - http://dev:8081/webhooks/livekit
ingress:
  whip_base_url: http://localhost:8080/whip